[package]
name = "physics-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30.11", features = ["wayland"] }
wgpu = "27.0.1"
env_logger = "0.11.8"
log = "0.4.27"
anyhow = "1.0.98"
futures = "0.3.31"
bytemuck = "1.23.1"
glam = { version = "0.30.4", features = ["bytemuck"] }
image = "0.25.6"
egui = "0.33.3"
egui-winit = "0.33.3"
egui-wgpu = "0.33.3"
